// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjmepwgsmzkwvmhrxkca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqbWVwd2dzbXprd3ZtaHJ4a2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MTMwMzUsImV4cCI6MjA1MzA4OTAzNX0.X5H6wMaVgPlLEuYGFTCiovHgFQ8tMasYsrB5ZVxUWOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);